var classes = [
    {
        "name": "App\\Controllers\\RecordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Models\\Record",
            "App\\Views\\RecordView"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 4,
        "volume": 18,
        "difficulty": 1,
        "effort": 18,
        "level": 1,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 18,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 2,
        "loc": 13,
        "lloc": 11,
        "mi": 96.91,
        "mIwoC": 68.36,
        "commentWeight": 28.55,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Record",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "PDO",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 22,
        "volume": 178.38,
        "difficulty": 3.11,
        "effort": 554.95,
        "level": 0.32,
        "bugs": 0.06,
        "time": 31,
        "intelligentContent": 57.34,
        "number_operators": 12,
        "number_operands": 28,
        "number_operators_unique": 4,
        "number_operands_unique": 18,
        "cloc": 6,
        "loc": 31,
        "lloc": 25,
        "mi": 84.97,
        "mIwoC": 53.47,
        "commentWeight": 31.5,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Views\\RecordView",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 11,
        "volume": 65.73,
        "difficulty": 3,
        "effort": 197.19,
        "level": 0.33,
        "bugs": 0.02,
        "time": 11,
        "intelligentContent": 21.91,
        "number_operators": 3,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 1,
        "loc": 78,
        "lloc": 75,
        "mi": 54.29,
        "mIwoC": 45.56,
        "commentWeight": 8.73,
        "kanDefect": 0.91,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Config\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 11,
        "vocabulary": 11,
        "volume": 38.05,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 76.11,
        "number_operators": 0,
        "number_operands": 11,
        "number_operators_unique": 0,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 62.53,
        "mIwoC": 62.53,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Config\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\AboutTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\BasketController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 41,
        "vocabulary": 14,
        "volume": 156.1,
        "difficulty": 4.23,
        "effort": 659.88,
        "level": 0.24,
        "bugs": 0.05,
        "time": 37,
        "intelligentContent": 36.93,
        "number_operators": 10,
        "number_operands": 31,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 5,
        "loc": 31,
        "lloc": 26,
        "mi": 82.38,
        "mIwoC": 53.24,
        "commentWeight": 29.14,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\CatalogueController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product",
            "App\\Views\\CatalogueTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 7,
        "volume": 39.3,
        "difficulty": 4.67,
        "effort": 183.41,
        "level": 0.21,
        "bugs": 0.01,
        "time": 10,
        "intelligentContent": 8.42,
        "number_operators": 7,
        "number_operands": 7,
        "number_operators_unique": 4,
        "number_operands_unique": 3,
        "cloc": 11,
        "loc": 26,
        "lloc": 15,
        "mi": 105.19,
        "mIwoC": 62.91,
        "commentWeight": 42.28,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\HomeTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildMessage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 11,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Services\\FileStorage",
            "App\\Models\\Order",
            "App\\Services\\OrderDBStorage",
            "App\\Models\\Order",
            "App\\Services\\UserDBStorage",
            "App\\Views\\OrderTemplate",
            "App\\Services\\FileStorage",
            "App\\Models\\Order",
            "App\\Services\\OrderDBStorage",
            "App\\Models\\Order",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 169,
        "vocabulary": 50,
        "volume": 953.81,
        "difficulty": 9.28,
        "effort": 8850.49,
        "level": 0.11,
        "bugs": 0.32,
        "time": 492,
        "intelligentContent": 102.79,
        "number_operators": 55,
        "number_operands": 114,
        "number_operators_unique": 7,
        "number_operands_unique": 43,
        "cloc": 13,
        "loc": 110,
        "lloc": 97,
        "mi": 59.71,
        "mIwoC": 34.32,
        "commentWeight": 25.39,
        "kanDefect": 0.94,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.41,
        "relativeSystemComplexity": 169.41,
        "totalStructuralComplexity": 676,
        "totalDataComplexity": 1.64,
        "totalSystemComplexity": 677.64,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product",
            "App\\Views\\ProductTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 24,
        "vocabulary": 10,
        "volume": 79.73,
        "difficulty": 7,
        "effort": 558.08,
        "level": 0.14,
        "bugs": 0.03,
        "time": 31,
        "intelligentContent": 11.39,
        "number_operators": 10,
        "number_operands": 14,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 6,
        "loc": 24,
        "lloc": 18,
        "mi": 93.74,
        "mIwoC": 58.76,
        "commentWeight": 34.97,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\RegisterController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Views\\RegisterTemplate",
            "App\\Services\\UserDBStorage",
            "App\\Models\\User",
            "App\\Services\\ValidateRegisterData",
            "App\\Services\\Mailer",
            "App\\Services\\UserDBStorage",
            "App\\Views\\RegisterTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 101,
        "vocabulary": 31,
        "volume": 500.37,
        "difficulty": 5.04,
        "effort": 2520.4,
        "level": 0.2,
        "bugs": 0.17,
        "time": 140,
        "intelligentContent": 99.34,
        "number_operators": 33,
        "number_operands": 68,
        "number_operators_unique": 4,
        "number_operands_unique": 27,
        "cloc": 6,
        "loc": 60,
        "lloc": 54,
        "mi": 65.89,
        "mIwoC": 42.37,
        "commentWeight": 23.53,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 49.79,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 2.38,
        "totalSystemComplexity": 149.38,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Controllers\\UserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "profile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "history",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 12,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Views\\UserTemplate",
            "App\\Services\\UserDBStorage",
            "App\\Views\\UserTemplate",
            "App\\Services\\UserDBStorage",
            "App\\Views\\UserTemplate",
            "App\\Services\\ValidateBase",
            "App\\Services\\UserDBStorage",
            "App\\Services\\UserDBStorage",
            "App\\Views\\UserTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 4,
        "length": 139,
        "vocabulary": 32,
        "volume": 695,
        "difficulty": 8.24,
        "effort": 5727.31,
        "level": 0.12,
        "bugs": 0.23,
        "time": 318,
        "intelligentContent": 84.34,
        "number_operators": 50,
        "number_operands": 89,
        "number_operators_unique": 5,
        "number_operands_unique": 27,
        "cloc": 11,
        "loc": 95,
        "lloc": 84,
        "mi": 61.66,
        "mIwoC": 36.51,
        "commentWeight": 25.15,
        "kanDefect": 0.92,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.82,
        "relativeSystemComplexity": 100.82,
        "totalStructuralComplexity": 600,
        "totalDataComplexity": 4.91,
        "totalSystemComplexity": 604.91,
        "package": "App\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBasketData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Services\\ISaveStorage",
            "App\\Services\\FileStorage",
            "App\\Models\\Product",
            "App\\Services\\ProductDBStorage",
            "App\\Models\\Product"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 131,
        "vocabulary": 33,
        "volume": 660.82,
        "difficulty": 10.56,
        "effort": 6975.28,
        "level": 0.09,
        "bugs": 0.22,
        "time": 388,
        "intelligentContent": 62.6,
        "number_operators": 36,
        "number_operands": 95,
        "number_operators_unique": 6,
        "number_operands_unique": 27,
        "cloc": 11,
        "loc": 69,
        "lloc": 58,
        "mi": 69.84,
        "mIwoC": 40.84,
        "commentWeight": 28.99,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.42,
        "relativeSystemComplexity": 5.42,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5.67,
        "totalSystemComplexity": 21.67,
        "package": "App\\Models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBasketData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\OrderValidator"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 131,
        "vocabulary": 33,
        "volume": 660.82,
        "difficulty": 8.75,
        "effort": 5782.14,
        "level": 0.11,
        "bugs": 0.22,
        "time": 321,
        "intelligentContent": 75.52,
        "number_operators": 33,
        "number_operands": 98,
        "number_operators_unique": 5,
        "number_operands_unique": 28,
        "cloc": 26,
        "loc": 88,
        "lloc": 62,
        "mi": 77.51,
        "mIwoC": 40.21,
        "commentWeight": 37.3,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 26,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 130,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 2.5,
        "effort": 84.01,
        "level": 0.4,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 13.44,
        "number_operators": 3,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 1,
        "loc": 16,
        "lloc": 15,
        "mi": 82.41,
        "mIwoC": 63.52,
        "commentWeight": 18.88,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "package": "App\\Models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Routers\\Router",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "route",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "executeRoute",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleDefault",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 9,
        "ccnMethodMax": 6,
        "externals": [
            "route",
            "App\\Controllers\\HomeController"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 146,
        "vocabulary": 47,
        "volume": 810.97,
        "difficulty": 5.67,
        "effort": 4601.78,
        "level": 0.18,
        "bugs": 0.27,
        "time": 256,
        "intelligentContent": 142.92,
        "number_operators": 24,
        "number_operands": 122,
        "number_operators_unique": 4,
        "number_operands_unique": 43,
        "cloc": 39,
        "loc": 81,
        "lloc": 42,
        "mi": 86.99,
        "mIwoC": 43.01,
        "commentWeight": 43.98,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.13,
        "relativeSystemComplexity": 26.13,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 104.5,
        "package": "App\\Routers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DatabaseStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage",
            "PDO"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 1,
        "length": 50,
        "vocabulary": 18,
        "volume": 208.5,
        "difficulty": 4.71,
        "effort": 982.91,
        "level": 0.21,
        "bugs": 0.07,
        "time": 55,
        "intelligentContent": 44.23,
        "number_operators": 17,
        "number_operands": 33,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 2,
        "loc": 34,
        "lloc": 32,
        "mi": 68.87,
        "mIwoC": 50.52,
        "commentWeight": 18.35,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.83,
        "relativeSystemComplexity": 25.83,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 77.5,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\DBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PDO"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 1,
        "loc": 10,
        "lloc": 9,
        "mi": 100.47,
        "mIwoC": 76.94,
        "commentWeight": 23.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Services\\",
        "pageRank": 0.08,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Services\\FileStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\ILoadStorage",
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 2,
        "length": 23,
        "vocabulary": 9,
        "volume": 72.91,
        "difficulty": 8.75,
        "effort": 637.95,
        "level": 0.11,
        "bugs": 0.02,
        "time": 35,
        "intelligentContent": 8.33,
        "number_operators": 9,
        "number_operands": 14,
        "number_operators_unique": 5,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 59.17,
        "mIwoC": 59.17,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Services\\Mailer",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "sendOrderMail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendMailUserConfirmation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 9,
        "ccnMethodMax": 5,
        "externals": [
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception",
            "PHPMailer\\PHPMailer\\PHPMailer",
            "PHPMailer\\PHPMailer\\Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 117,
        "vocabulary": 26,
        "volume": 549.95,
        "difficulty": 11.7,
        "effort": 6434.43,
        "level": 0.09,
        "bugs": 0.18,
        "time": 357,
        "intelligentContent": 47,
        "number_operators": 39,
        "number_operands": 78,
        "number_operators_unique": 6,
        "number_operands_unique": 20,
        "cloc": 12,
        "loc": 81,
        "lloc": 69,
        "mi": 67.57,
        "mIwoC": 39.49,
        "commentWeight": 28.08,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 36.86,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.71,
        "totalSystemComplexity": 73.71,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveItems",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 1,
        "length": 80,
        "vocabulary": 28,
        "volume": 384.59,
        "difficulty": 4.02,
        "effort": 1546.05,
        "level": 0.25,
        "bugs": 0.13,
        "time": 86,
        "intelligentContent": 95.67,
        "number_operators": 13,
        "number_operands": 67,
        "number_operators_unique": 3,
        "number_operands_unique": 25,
        "cloc": 6,
        "loc": 33,
        "lloc": 27,
        "mi": 81.09,
        "mIwoC": 50.41,
        "commentWeight": 30.68,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 16.8,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.6,
        "totalSystemComplexity": 33.6,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPDO",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\ISaveStorage",
            "PDO",
            "PDO"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 2,
        "length": 37,
        "vocabulary": 23,
        "volume": 167.37,
        "difficulty": 1.52,
        "effort": 255.04,
        "level": 0.66,
        "bugs": 0.06,
        "time": 14,
        "intelligentContent": 109.84,
        "number_operators": 5,
        "number_operands": 32,
        "number_operators_unique": 2,
        "number_operands_unique": 21,
        "cloc": 2,
        "loc": 21,
        "lloc": 19,
        "mi": 79.4,
        "mIwoC": 56.4,
        "commentWeight": 23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderValidator",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrors",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCleanData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateFio",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateEmail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatePhone",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateAddress",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateBasket",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateComment",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 7,
        "nbMethodsPrivate": 6,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 20,
        "ccnMethodMax": 8,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 209,
        "vocabulary": 48,
        "volume": 1167.26,
        "difficulty": 16.85,
        "effort": 19663.79,
        "level": 0.06,
        "bugs": 0.39,
        "time": 1092,
        "intelligentContent": 69.29,
        "number_operators": 63,
        "number_operands": 146,
        "number_operators_unique": 9,
        "number_operands_unique": 39,
        "cloc": 14,
        "loc": 116,
        "lloc": 102,
        "mi": 57.65,
        "mIwoC": 32.02,
        "commentWeight": 25.63,
        "kanDefect": 1.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.98,
        "relativeSystemComplexity": 37.98,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 17.86,
        "totalSystemComplexity": 341.86,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ILoadStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ILoadStorage"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 8,
        "volume": 39,
        "difficulty": 1.5,
        "effort": 58.5,
        "level": 0.67,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 26,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 66.01,
        "mIwoC": 66.01,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 4.67,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 3,
        "efferentCoupling": 2,
        "instability": 0.4,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Services\\ILoadStorage",
            "PDO"
        ],
        "parents": [],
        "implements": [
            "App\\Services\\ILoadStorage"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 7,
        "volume": 33.69,
        "difficulty": 1.8,
        "effort": 60.64,
        "level": 0.56,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 18.72,
        "number_operators": 3,
        "number_operands": 9,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 64.03,
        "mIwoC": 64.03,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 9.33,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\UserDBStorage",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "uniqueEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveVerified",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loginUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDataHistory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Services\\DBStorage",
            "App\\Services\\ISaveStorage"
        ],
        "parents": [
            "App\\Services\\DBStorage"
        ],
        "implements": [
            "App\\Services\\ISaveStorage"
        ],
        "lcom": 1,
        "length": 140,
        "vocabulary": 39,
        "volume": 739.96,
        "difficulty": 9.27,
        "effort": 6861.41,
        "level": 0.11,
        "bugs": 0.25,
        "time": 381,
        "intelligentContent": 79.8,
        "number_operators": 38,
        "number_operands": 102,
        "number_operators_unique": 6,
        "number_operands_unique": 33,
        "cloc": 8,
        "loc": 82,
        "lloc": 74,
        "mi": 61.45,
        "mIwoC": 38.19,
        "commentWeight": 23.26,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.79,
        "relativeSystemComplexity": 50.79,
        "totalStructuralComplexity": 343,
        "totalDataComplexity": 12.5,
        "totalSystemComplexity": 355.5,
        "package": "App\\Services\\",
        "pageRank": 0.04,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Services\\ValidateBase",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "sanitationString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sanitationArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 10,
        "vocabulary": 4,
        "volume": 20,
        "difficulty": 1.5,
        "effort": 30,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 13.33,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 65.62,
        "mIwoC": 65.62,
        "commentWeight": 0,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 3,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Services\\ValidateRegisterData",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 10,
        "ccnMethodMax": 10,
        "externals": [
            "App\\Services\\UserDBStorage"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 76,
        "vocabulary": 24,
        "volume": 348.46,
        "difficulty": 7.67,
        "effort": 2671.5,
        "level": 0.13,
        "bugs": 0.12,
        "time": 148,
        "intelligentContent": 45.45,
        "number_operators": 30,
        "number_operands": 46,
        "number_operators_unique": 6,
        "number_operands_unique": 18,
        "cloc": 1,
        "loc": 44,
        "lloc": 43,
        "mi": 56.79,
        "mIwoC": 45.22,
        "commentWeight": 11.57,
        "kanDefect": 0.78,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 6,
        "package": "App\\Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\AboutTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 1.67,
        "effort": 27.09,
        "level": 0.6,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 9.75,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 13,
        "loc": 64,
        "lloc": 45,
        "mi": 87.47,
        "mIwoC": 55.32,
        "commentWeight": 32.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\BaseTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 43,
        "vocabulary": 18,
        "volume": 179.31,
        "difficulty": 7.5,
        "effort": 1344.8,
        "level": 0.13,
        "bugs": 0.06,
        "time": 75,
        "intelligentContent": 23.91,
        "number_operators": 13,
        "number_operands": 30,
        "number_operators_unique": 6,
        "number_operands_unique": 12,
        "cloc": 5,
        "loc": 122,
        "lloc": 112,
        "mi": 54.41,
        "mIwoC": 38.98,
        "commentWeight": 15.43,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.24,
        "afferentCoupling": 7,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Views\\CatalogueTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getCatalogue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 64,
        "vocabulary": 27,
        "volume": 304.31,
        "difficulty": 5.34,
        "effort": 1625.31,
        "level": 0.19,
        "bugs": 0.1,
        "time": 90,
        "intelligentContent": 56.98,
        "number_operators": 17,
        "number_operands": 47,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 2,
        "loc": 70,
        "lloc": 63,
        "mi": 55.5,
        "mIwoC": 42.55,
        "commentWeight": 12.94,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\HomeTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 5,
        "volume": 16.25,
        "difficulty": 1.67,
        "effort": 27.09,
        "level": 0.6,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 9.75,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 1,
        "loc": 34,
        "lloc": 33,
        "mi": 71.39,
        "mIwoC": 58.26,
        "commentWeight": 13.13,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "App\\Views\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\OrderTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getOrderTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 14,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 107,
        "vocabulary": 32,
        "volume": 535,
        "difficulty": 15.26,
        "effort": 8164.57,
        "level": 0.07,
        "bugs": 0.18,
        "time": 454,
        "intelligentContent": 35.06,
        "number_operators": 29,
        "number_operands": 78,
        "number_operators_unique": 9,
        "number_operands_unique": 23,
        "cloc": 17,
        "loc": 130,
        "lloc": 112,
        "mi": 60.88,
        "mIwoC": 34.31,
        "commentWeight": 26.57,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 5,
        "package": "App\\Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\ProductTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getCatalogue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCardTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 76,
        "vocabulary": 30,
        "volume": 372.92,
        "difficulty": 7.13,
        "effort": 2657.08,
        "level": 0.14,
        "bugs": 0.12,
        "time": 148,
        "intelligentContent": 52.34,
        "number_operators": 19,
        "number_operands": 57,
        "number_operators_unique": 6,
        "number_operands_unique": 24,
        "cloc": 25,
        "loc": 139,
        "lloc": 109,
        "mi": 67.15,
        "mIwoC": 36.61,
        "commentWeight": 30.54,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 6,
        "package": "App\\Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\RegisterTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getRegisterTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVerifyTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 25,
        "vocabulary": 12,
        "volume": 89.62,
        "difficulty": 2.83,
        "effort": 253.93,
        "level": 0.35,
        "bugs": 0.03,
        "time": 14,
        "intelligentContent": 31.63,
        "number_operators": 8,
        "number_operands": 17,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 32,
        "loc": 78,
        "lloc": 46,
        "mi": 91.79,
        "mIwoC": 49.92,
        "commentWeight": 41.86,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "package": "App\\Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Views\\UserTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getUserTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProfileTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFormProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHistoryTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 11,
        "ccnMethodMax": 9,
        "externals": [
            "App\\Views\\BaseTemplate"
        ],
        "parents": [
            "App\\Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 5,
        "length": 137,
        "vocabulary": 35,
        "volume": 702.71,
        "difficulty": 10.34,
        "effort": 7269.43,
        "level": 0.1,
        "bugs": 0.23,
        "time": 404,
        "intelligentContent": 67.93,
        "number_operators": 37,
        "number_operands": 100,
        "number_operators_unique": 6,
        "number_operands_unique": 29,
        "cloc": 14,
        "loc": 125,
        "lloc": 112,
        "mi": 58.66,
        "mIwoC": 33.89,
        "commentWeight": 24.78,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.4,
        "relativeSystemComplexity": 10.4,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 52,
        "package": "App\\Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]